### ISSUE TITLE
Error on update.

### ISSUE THREAD

**Issue by Donklord** [Fantom-Factory/fantom-lang.org#1]
I get the following error when running an update.

C:\Users\Phillip Birch\Documents\GitHub\fantom-lang.org>fpm update
FPM updating dependencies for afFantomLang ...
 - found afBeanUtils 1.0.8, 1.0.10
 - found afConcurrent 1.0.20, 1.0.22, 1.0.24
 - found afIoc 3.0.6
 - found afIocConfig 1.1.0
 - found afIocEnv 1.1.0
 - found afBedSheet 1.5.10, 1.5.12
 - found afPillow 1.1.4
 - found afEfanXtra 1.2.0
 - found afColdFeet 1.4.0
 - found afDuvet 1.1.8
 - found afSlim 1.2.0
 - found afSitemap 1.1.0
 - found afGoogleAnalytics 0.1.4, 0.1.6, 0.1.8
 - found afAskFanny 0.0.4
 - found afSleepSafe 1.0.0, 1.0.2
 - found afIoc 3.0.4, 3.0.6
 - found afIoc 3.0.0, 3.0.2, 3.0.4, 3.0.6
 - found afBeanUtils 1.0.6, 1.0.8, 1.0.10
 - found afConcurrent 1.0.16, 1.0.18, 1.0.20, 1.0.22, 1.0.24
 - found afPlastic 1.1.0, 1.1.2, 1.1.4
 - found afBedSheet 1.5.6, 1.5.8, 1.5.10, 1.5.12
 - found afEfan 1.5.0, 1.5.2
 - found afBedSheet 1.5.4, 1.5.6, 1.5.8, 1.5.10, 1.5.12
 - found afPegger 0.1.0
 - found afPillow 1.1.0, 1.1.2, 1.1.4
 - found afDuvet 1.1.0, 1.1.2, 1.1.4, 1.1.6, 1.1.8
 - found afConcurrent 1.0.20, 1.0.22, 1.0.24
sys::IOErr: Could not find `/meta.props` in pod file: C:\fantom\fantom-1.0.73\lib\fan\afBeanUtils.pod
  afFpm::FileUtils$.readMetaProps (FileUtils.fan:36)
  afFpm::LocalDirRepository.readMetaProps (LocalDirRepository.fan:71)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:57)
  fan.sys.Func$Indirect0.call (Func.java:128)
  fan.sys.Map.getOrAdd (Map.java:168)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:56)
  afFpm::LocalDirRepository.upload (LocalDirRepository.fan:23)
  afFpm::PodFile.installTo (PodFile.fan:61)
  afFpm::InstallCmd.run (InstallCmd.fan:114)
  fan.sys.Func$Indirect1.call (Func.java:145)
  fan.sys.Map.each (Map.java:367)
  afFpm::InstallCmd.run (InstallCmd.fan:113)
  afFpm::Main.main (Main.fan:40)
  java.lang.reflect.Method.invoke (Unknown)
  fan.sys.Method.invoke (Method.java:573)
  fan.sys.Method$MethodFunc.callOn (Method.java:244)
  fan.sys.Method.callOn (Method.java:139)
  fanx.tools.Fan.callMain (Fan.java:185)
  fanx.tools.Fan.executeType (Fan.java:147)
  fanx.tools.Fan.execute (Fan.java:41)
  fanx.tools.Fan.run (Fan.java:308)
  fanx.tools.Fan.main (Fan.java:346)

**Comment by SlimerDude** [comment]
Hi Donklord,

Thanks for reporting... that looks to be an issue with [FPM](https://github.com/SlimerDude/afFpm) rather than fantom-lang. It seems the `update` command, in an attempt to update **all** dependencies, tries to overwrite files with themselves (!?) - hence the file errors.

For now you can work around it by installing pods into a work directory (which is usually better practice):

    > set FAN_ENV_PATH=C:\fantom\fantom-1.0.73\var
    > mkdir C:\fantom\fantom-1.0.73\var

    > fpm update -d -r workDir
    > fpm build
    > fpm run afFantomLang 8069

Then if you get any problems, you can just nuke the `var/` directory.

**Comment by Donklord** [comment]
Sorry about the stupid questions!  Im still getting used to fantom outside of SkySpark!  When running the above, i get the same error on the fpm update.

C:\fantom\fantom-1.0.73\fantom-lang.org>fpm update -d -r workDir
ERROR: Env.index load: afBeanUtils
  java.util.zip.ZipException: zip file is empty
FPM updating dependencies for afFantomLang ...
sys::IOErr: Could not find `/meta.props` in pod file: C:\fantom\fantom-1.0.73\lib\fan\afBeanUtils.pod
  afFpm::FileUtils$.readMetaProps (FileUtils.fan:36)
  afFpm::LocalDirRepository.readMetaProps (LocalDirRepository.fan:71)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:57)
  fan.sys.Func$Indirect0.call (Func.java:128)
  fan.sys.Map.getOrAdd (Map.java:168)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:56)
  afFpm::LocalDirRepository.resolve (LocalDirRepository.fan:40)
  afFpm::Resolver.doResolve (Resolver.fan:117)
  fan.sys.List.each (List.java:602)
  afFpm::Resolver.doResolve (Resolver.fan:116)
  afFpm::Resolver.resolve (Resolver.fan:105)
  fan.sys.Func$Indirect0.call (Func.java:128)
  fan.sys.Map.getOrAdd (Map.java:168)
  afFpm::Resolver.resolve (Resolver.fan:93)
  afFpm::Satisfier.resolveNode (Satisfier.fan:347)
  afFpm::Satisfier.make (Satisfier.fan:57)
  fan.sys.List.each (List.java:602)
  afFpm::Satisfier.make$ (Satisfier.fan:56)
  afFpm::Satisfier.make (Satisfier.fan:27)
  afFpm::Resolver.satisfy (Resolver.fan:72)
  afFpm::Resolver.satisfyBuild (Resolver.fan:68)
  afFpm::InstallCmd.run (InstallCmd.fan:106)
  afFpm::Main.main (Main.fan:40)
  java.lang.reflect.Method.invoke (Unknown)
  fan.sys.Method.invoke (Method.java:573)
  6 More...

**Comment by SlimerDude** [comment]
No worries, `fantom-1.0.73\lib\fan\afBeanUtils.pod` will be corrupt again (from an earlier invocation of FPM) - so just delete it. On my machine, corrupted files were easy to spot because they had 0 bytes.

With the work around, `fantom-1.0.73\lib\fan\` can now be a clean install, with no `af*` pods. If in doubt, copy pods over from from a fresh Fantom download.

Before you `fpm update` again, make sure you see something similar to the following when you type `fpm`:

    C:\...\fantom-lang.org> fpm

    FPM (2.0.6) Environment:
          Base Dir : C:\fantom\fantom-1.0.73\fantom-lang.org
      Fan Home Dir : C:\fantom\fantom-1.0.73
         Work Dirs : C:\fantom\fantom-1.0.73\var            <-- THIS
                     C:\fantom\fantom-1.0.73
          Temp Dir : C:\fantom\fantom-1.0.73\var\temp (does not exist)
      Config Files : C:\fantom\fantom-1.0.73\etc\afFpm\fpm.props
    
         Dir Repos :
           default = C:\fantom\fantom-1.0.73\lib\fan
               lib = C:\fantom\fantom-1.0.73\fantom-lang.org\lib (does not exist)
            libfan = C:\fantom\fantom-1.0.73\fantom-lang.org\lib\fan (does not exist)
           workDir = C:\fantom\fantom-1.0.73\var\lib\fan    <-- THIS
           fanHome = C:\fantom\fantom-1.0.73\lib\fan
    
        Fanr Repos :
            eggbox = http://eggbox.fantomfactory.org/fanr/
    
            Macros :
           fanHome = file:/C:/fantom/fantom-1.0.73/
    
The `workDir`, or the `var/` dir in your case (that comes from setting the `FAN_ENV_PATH` environment variable) is where the new pods will be downloaded / copied too so FPM doesn't try to overwrite your core Fantom pods.

**Comment by SlimerDude** [comment]
If you download [FPM v2.0.8](http://eggbox.fantomfactory.org/pods/afFpm/), that should resolve this issue.

*(Just make sure to delete all corrupted pod files first!)*
